// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CheckMyStar.Data;

public partial class CheckMyStarDbContext : DbContext
{
    public CheckMyStarDbContext(DbContextOptions<CheckMyStarDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Accommodation> Accommodations { get; set; }

    public virtual DbSet<AccommodationType> AccommodationTypes { get; set; }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<Assessment> Assessments { get; set; }

    public virtual DbSet<AssessmentCriterion> AssessmentCriteria { get; set; }

    public virtual DbSet<Civility> Civilities { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Criterion> Criteria { get; set; }

    public virtual DbSet<CriterionType> CriterionTypes { get; set; }

    public virtual DbSet<Folder> Folders { get; set; }

    public virtual DbSet<FolderStatus> FolderStatuses { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Quote> Quotes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Society> Societies { get; set; }

    public virtual DbSet<StarLevel> StarLevels { get; set; }

    public virtual DbSet<StarLevelCriterion> StarLevelCriteria { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Accommodation>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Accommodation");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.AccommodationName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.AccommodationPhone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<AccommodationType>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("AccommodationType");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Activity");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Date).HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Address");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.AddressLine)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.City)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Number)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Region)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            entity.Property(e => e.ZipCode)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Appointment>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Appointment");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.AppointmentDate).HasColumnType("datetime");
            entity.Property(e => e.Comment)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Assessment");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SmallestRoomArea).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalArea).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TotalRoomsArea).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<AssessmentCriterion>(entity =>
        {
            entity.HasKey(e => new { e.AssessmentIdentifier, e.CriterionId }).HasName("PK_EvaluationCriterion");

            entity.ToTable("AssessmentCriterion");

            entity.Property(e => e.Comment)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Civility>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Civility");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Country");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Code)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Criterion>(entity =>
        {
            entity.ToTable("Criterion");

            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CriterionType>(entity =>
        {
            entity.HasKey(e => e.TypeCode);

            entity.ToTable("CriterionType");

            entity.Property(e => e.TypeCode)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Label)
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Folder>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Folder");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<FolderStatus>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("FolderStatus");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Label)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Invoice");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DueDate).HasColumnType("datetime");
            entity.Property(e => e.Number)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Quote>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Quote");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Reference)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Role");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<Society>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Society");

            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<StarLevel>(entity =>
        {
            entity.ToTable("StarLevel");

            entity.Property(e => e.Label).HasMaxLength(30);
            entity.Property(e => e.LastUpdate).HasColumnType("datetime");
        });

        modelBuilder.Entity<StarLevelCriterion>(entity =>
        {
            entity.HasKey(e => new { e.StarLevelId, e.CriterionId });

            entity.ToTable("StarLevelCriterion");

            entity.Property(e => e.TypeCode)
                .HasMaxLength(5)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("User");

            entity.Property(e => e.Identifier).ValueGeneratedNever();
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsFirstConnection).HasDefaultValue(true);
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(64)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}