using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for accommodation operations.
    /// </summary>
    /// <param name="accommodationService">Accommodation service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class AccommodationController(IAccommodationService accommodationService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for an accommodation. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying accommodation service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available accommodation identifier.</returns>
        [HttpPost("getnextidentifier")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await accommodationService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Retrieves all active accommodations.
        /// </summary>
        /// <remarks>Returns only accommodations where IsActive = true.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of active accommodations.</returns>
        [HttpGet("getaccommodations")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetAccommodations(CancellationToken ct)
        {
            var result = await accommodationService.GetAccommodations(ct);

            return Ok(result);
        }

        /// <summary>
        /// Creates a new accommodation using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - The AccommodationTypeIdentifier must exist in the AccommodationType table
        /// - The AddressIdentifier must exist in the Address table
        /// - IsActive is automatically set to true
        /// </remarks>
        /// <param name="request">The details of the accommodation to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the accommodation creation.</returns>
        [HttpPost("createaccommodation")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAccommodation([FromBody] AccommodationSaveRequest request, CancellationToken ct)
        {
            var result = await accommodationService.CreateAccommodation(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Deletes an accommodation by its identifier.
        /// </summary>
        /// <remarks>
        /// This endpoint permanently deletes an accommodation from the database.
        /// Use with caution as this action cannot be undone.
        /// </remarks>
        /// <param name="accommodationIdentifier">The unique identifier of the accommodation to delete.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the deletion operation.</returns>
        [HttpDelete("deleteaccommodation/{accommodationIdentifier}")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteAccommodation(int accommodationIdentifier, CancellationToken ct)
        {
            var result = await accommodationService.DeleteAccommodation(accommodationIdentifier, ct);

            return Ok(result);
        }
    }
}
