using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for accommodation operations.
    /// </summary>
    /// <param name="accommodationService">Accommodation service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class AccommodationController(IAccommodationService accommodationService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for an accommodation. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying accommodation service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available accommodation identifier.</returns>
        [HttpGet("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await accommodationService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Retrieves all active accommodations.
        /// </summary>
        /// <remarks>Returns only accommodations where IsActive = true.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of active accommodations.</returns>
        [HttpGet("getaccommodations")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetAccommodations(CancellationToken ct)
        {
            var result = await accommodationService.GetAccommodations(ct);

            return Ok(result);
        }

        /// <summary>
        /// Creates a new accommodation using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - The AccommodationTypeIdentifier must exist in the AccommodationType table
        /// - The AddressIdentifier must exist in the Address table
        /// - IsActive is automatically set to true
        /// </remarks>
        /// <param name="request">The details of the accommodation to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the accommodation creation.</returns>
        [HttpPost("createaccommodation")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> CreateAccommodation([FromBody] AccommodationSaveRequest request, CancellationToken ct)
        {
            var result = await accommodationService.CreateAccommodation(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Updates an existing accommodation using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - The accommodation must exist
        /// - The AccommodationTypeIdentifier must exist in the AccommodationType table
        /// - The AddressIdentifier must exist in the Address table
        /// </remarks>
        /// <param name="request">The details of the accommodation to update. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the accommodation update.</returns>
        [HttpPut("updateaccommodation")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> UpdateAccommodation([FromBody] AccommodationSaveRequest request, CancellationToken ct)
        {
            var result = await accommodationService.UpdateAccommodation(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Deletes the specified accommodation asynchronously based on the provided identifier.
        /// </summary>
        /// <remarks>This method requires the caller to have either Administrator or Inspector roles. The
        /// operation is performed asynchronously and returns an appropriate response based on the result.</remarks>
        /// <param name="request">An object containing the details of the accommodation to be deleted, including its unique identifier.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the deletion operation.</param>
        /// <returns>An IActionResult that indicates the outcome of the deletion operation. Returns a success response if the
        /// accommodation is deleted; otherwise, returns an error response.</returns>
        [HttpDelete("deleteaccommodation")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> DeleteAccommodation(AccommodationDeleteRequest request, CancellationToken ct)
        {
            var result = await accommodationService.DeleteAccommodation(request, ct);

            return Ok(result);
        }
    }
}
