using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for address operations.
    /// </summary>
    /// <param name="addressService">Address service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class AddressController(IAddressService addressService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for an address. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying address service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available address identifier.</returns>
        [HttpPost("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await addressService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Creates a new address using the specified request data.
        /// </summary>
        /// <param name="request">The details of the address to create (numéro de rue, rue, ville, code postal, région, pays). Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the address creation.</returns>
        [HttpPost("addaddress")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AddAddress([FromBody] AddressSaveRequest request, CancellationToken ct)
        {
            var result = await addressService.AddAddress(request, ct);

            return Ok(result);
        }
    }
}