using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for address operations.
    /// </summary>
    /// <param name="addressService"></param>    
    [ApiController]
    [Route("api/[controller]")]
    public class AddressController(IAddressService addressService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for an address. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying address service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available address identifier.</returns>
        [HttpPost("getnextidentifier")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await addressService.GetNextIdentifier(ct);

            return Ok(identifier);
        }
    }
}
