using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for address operations.
    /// </summary>
    /// <param name="addressService">Address service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class AddressController(IAddressService addressService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for an address. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying address service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available address identifier.</returns>
        [HttpGet("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await addressService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Get addresses matching the specified criteria. The search can be filtered by any combination of the following parameters: numéro de rue, rue, ville, code postal, région, pays.
        /// </summary>
        /// <param name="request">The criteria for filtering addresses. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the addresses that match the specified criteria.</returns>
        [HttpGet("getaddresses")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetAddresses([FromQuery] AddressGetRequest request, CancellationToken ct)
        {
            var result = await addressService.GetAddresses(request, ct);

            return Ok(result);
        }


        /// <summary>
        /// Creates a new address using the specified request data.
        /// </summary>
        /// <param name="request">The details of the address to create (numéro de rue, rue, ville, code postal, région, pays). Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the address creation.</returns>
        [HttpPost("addaddress")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> AddAddress([FromBody] AddressSaveRequest request, CancellationToken ct)
        {
            var result = await addressService.AddAddress(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Updates an existing address using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates that the address exists before updating it.
        /// </remarks>
        /// <param name="request">The details of the address to update (numéro de rue, rue, ville, code postal, région, pays). Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the address update.</returns>
        [HttpPut("updateaddress")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> UpdateAddress([FromBody] AddressSaveRequest request, CancellationToken ct)
        {
            var result = await addressService.UpdateAddress(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Deletes the specified address from the system asynchronously.
        /// </summary>
        /// <remarks>This method requires the caller to have either Administrator or Inspector roles. The
        /// operation is performed asynchronously.</remarks>
        /// <param name="request">The address details to be deleted, provided as an AddressSaveRequest object. Cannot be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the delete operation.</param>
        /// <returns>An IActionResult that indicates the outcome of the delete operation. Returns a success or failure status.</returns>
        [HttpDelete("deleteaddress")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> DeleteAddress([FromQuery] AddressDeleteRequest request, CancellationToken ct)
        {
            var result = await addressService.DeleteAddress(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Search an exinsting address using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates that the address exists.
        /// </remarks>
        /// <param name="request">The details of the address (numéro de rue, rue, ville, code postal). Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the address.</returns>
        [HttpGet("searchaddress")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> SearchAddress([FromQuery] GeolocationGetRequest request, CancellationToken ct)
        {
            var result = await addressService.SearchAddress(request, ct);

            return Ok(result);
        }
    }
}