using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;
using CheckMyStar.Bll.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for folder operations.
    /// </summary>
    /// <param name="folderService">Folder service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class FolderController(IFolderService folderService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for a folder. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying folder service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available folder identifier.</returns>
        [HttpGet("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await folderService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Retrieves all folders with their complete information.
        /// </summary>
        /// <remarks>Returns all folders with AccommodationType, Accommodation, OwnerUser, InspectorUser, FolderStatus, Quote, Invoice, and Appointment data.</remarks>
        /// <param name="request">The filter criteria for retrieving folders. All properties are optional and can be used to narrow down the results.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of folders.</returns>
        [HttpGet("getfolders")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetFolders([FromQuery] FolderGetRequest request, CancellationToken ct)
        {
            var result = await folderService.GetFolders(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Retrieves the details of a folder based on the specified identifier.
        /// </summary>
        /// <remarks>This method requires the caller to have either Administrator or Inspector roles. The
        /// operation is asynchronous and can be canceled using the provided cancellation token.</remarks>
        /// <param name="request">The request object containing the identifier of the folder to retrieve. Cannot be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An IActionResult containing the folder details if found; otherwise, an appropriate error response.</returns>
        [HttpGet("getfolder")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetFolder([FromQuery] FolderGetRequest request, CancellationToken ct)
        {
            var result = await folderService.GetFolder(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Retrieves a list of folders associated with the specified inspector based on the provided request
        /// parameters.
        /// </summary>
        /// <remarks>This method requires the caller to have either the Administrator or Inspector role.
        /// Ensure that the request parameters are valid to avoid errors.</remarks>
        /// <param name="request">The request object containing the criteria for retrieving folders, such as filters or pagination options.
        /// Cannot be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An IActionResult containing the list of folders associated with the inspector. Returns a 200 OK response
        /// with the folder data if successful.</returns>
        [HttpGet("getfoldersbyinspector")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetFoldersByInspector([FromQuery] FolderGetRequest request, CancellationToken ct)
        {
            var result = await folderService.GetFoldersByInspector(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Creates a new folder using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - AccommodationTypeIdentifier must exist in AccommodationType table
        /// - AccommodationIdentifier must exist in Accommodation table
        /// - OwnerUserIdentifier must exist in User table
        /// - InspectorUserIdentifier must exist in User table
        /// - FolderStatusIdentifier must exist in FolderStatus table
        /// - QuoteIdentifier (optional) must exist in Quote table
        /// - InvoiceIdentifier (optional) must exist in Invoice table
        /// - AppointmentIdentifier (optional) must exist in Appointment table
        /// - CreatedDate is automatically set
        /// </remarks>
        /// <param name="request">The details of the folder to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the folder creation.</returns>
        [HttpPost("addfolder")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> AddFolder([FromBody] FolderSaveRequest request, CancellationToken ct)
        {
            var result = await folderService.CreateFolder(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Updates an existing folder using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - The folder must exist
        /// - AccommodationTypeIdentifier must exist in AccommodationType table
        /// - AccommodationIdentifier must exist in Accommodation table
        /// - OwnerUserIdentifier must exist in User table
        /// - InspectorUserIdentifier must exist in User table
        /// - FolderStatusIdentifier must exist in FolderStatus table
        /// - QuoteIdentifier (optional) must exist in Quote table
        /// - InvoiceIdentifier (optional) must exist in Invoice table
        /// - AppointmentIdentifier (optional) must exist in Appointment table
        /// </remarks>
        /// <param name="request">The details of the folder to update. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the folder update.</returns>
        [HttpPut("updatefolder")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> UpdateFolder([FromBody] FolderSaveRequest request, CancellationToken ct)
        {
            var result = await folderService.UpdateFolder(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Deletes an existing folder by identifier.
        /// </summary>
        /// <remarks>This endpoint deletes a folder from the system. The operation is logged to the activity table for audit purposes.</remarks>
        /// <param name="request">The request of the folder to delete.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the folder deletion.</returns>
        [HttpDelete("deletefolder")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> DeleteFolder([FromQuery] FolderDeleteRequest request, CancellationToken ct)
        {
            var result = await folderService.DeleteFolder(request, ct);

            return Ok(result);
        }
    }
}
