using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for folder operations.
    /// </summary>
    /// <param name="folderService">Folder service</param>    
    [ApiController]
    [Route("api/[controller]")]
    public class FolderController(IFolderService folderService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for a folder. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying folder service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available folder identifier.</returns>
        [HttpPost("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await folderService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Retrieves all folders with their complete information.
        /// </summary>
        /// <remarks>Returns all folders with AccommodationType, Accommodation, OwnerUser, InspectorUser, FolderStatus, Quote, Invoice, and Appointment data.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of folders.</returns>
        [HttpGet("getfolders")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetFolders(CancellationToken ct)
        {
            var result = await folderService.GetFolders(ct);

            return Ok(result);
        }

        /// <summary>
        /// Creates a new folder using the specified request data.
        /// </summary>
        /// <remarks>
        /// This endpoint validates:
        /// - AccommodationTypeIdentifier must exist in AccommodationType table
        /// - AccommodationIdentifier must exist in Accommodation table
        /// - OwnerUserIdentifier must exist in User table
        /// - InspectorUserIdentifier must exist in User table
        /// - FolderStatusIdentifier must exist in FolderStatus table
        /// - QuoteIdentifier (optional) must exist in Quote table
        /// - InvoiceIdentifier (optional) must exist in Invoice table
        /// - AppointmentIdentifier (optional) must exist in Appointment table
        /// - CreatedDate is automatically set
        /// </remarks>
        /// <param name="request">The details of the folder to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the folder creation.</returns>
        [HttpPost("createfolder")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> CreateFolder([FromBody] FolderSaveRequest request, CancellationToken ct)
        {
            var result = await folderService.CreateFolder(request, ct);

            return Ok(result);
        }

        /// <summary>
        /// Deletes an existing folder by identifier.
        /// </summary>
        /// <remarks>This endpoint deletes a folder from the system. The operation is logged to the activity table for audit purposes.</remarks>
        /// <param name="folderIdentifier">The unique identifier of the folder to delete.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the result of the folder deletion.</returns>
        [HttpDelete("deletefolder/{folderIdentifier}")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> DeleteFolder(int folderIdentifier, CancellationToken ct)
        {
            var result = await folderService.DeleteFolder(folderIdentifier, ct);

            return Ok(result);
        }
    }
}
