using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for quote operations.
    /// </summary>
    /// <param name="quoteService">Quote service</param>
    [ApiController]
    [Route("api/[controller]")]
    public class QuoteController(IQuoteService quoteService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for a quote.
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator or Inspector role. The identifier is
        /// generated by the underlying quote service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the next available quote identifier.</returns>
        [HttpGet("getnextidentifier")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await quoteService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Get all quotes
        /// </summary>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>A list of all quotes.</returns>
        [HttpGet("getquotes")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetQuotes(CancellationToken ct)
        {
            var quotes = await quoteService.GetQuotes(ct);

            return Ok(quotes);
        }

        /// <summary>
        /// Get quotes by inspector
        /// </summary>
        /// <param name="request">The criteria for retrieving quotes. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>A list of quotes matching the specified criteria.</returns>
        [HttpGet("getquotesbyinspector")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GetQuotesByInspector([FromQuery] QuoteGetRequest request, CancellationToken ct)
        {
            var quotes = await quoteService.GetQuotes(request, ct);

            return Ok(quotes);
        }

        /// <summary>
        /// Génère un PDF simple à partir d'un devis existant.
        /// </summary>
        /// <param name="identifier">Identifiant du devis à exporter.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>Un fichier PDF du devis si la génération est réussie.</returns>
        [HttpGet("generatepdf/{identifier:int}")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> GeneratePdf(int identifier, CancellationToken ct)
        {
            var pdfResponse = await quoteService.GenerateQuotePdf(identifier, ct);

            if (!pdfResponse.IsSuccess || pdfResponse.Content == null || pdfResponse.Content.Length == 0)
            {
                if (pdfResponse.Message == "Devis non trouvé")
                {
                    return NotFound(pdfResponse);
                }

                return BadRequest(pdfResponse);
            }

            return File(pdfResponse.Content, "application/pdf", pdfResponse.FileName);
        }

        /// <summary>
        /// Creates a new quote with the specified details.
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator or Inspector role. The request must
        /// include all required quote information in the request body, including quote lines (prestations). 
        /// Each quote line should include: Description, Quantity, Unit, UnitPriceHT, and VATRate.
        /// The created date is automatically set.</remarks>
        /// <param name="request">The quote information to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the created quote information if successful.</returns>
        [HttpPost("addquote")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> AddQuote([FromBody] QuoteSaveRequest request, CancellationToken ct)
        {
            var quote = await quoteService.AddQuote(request, ct);

            return Ok(quote);
        }

        /// <summary>
        /// Updates an existing quote with the specified details.
        /// </summary>
        /// <remarks>Only quotes with IsEditable set to true can be updated. 
        /// The quote lines will be completely replaced with the new ones provided in the request.</remarks>
        /// <param name="request">The quote information to update. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the updated quote information if the update is successful.</returns>
        [HttpPut("updatequote")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> UpdateQuote([FromBody] QuoteSaveRequest request, CancellationToken ct)
        {
            var quote = await quoteService.UpdateQuote(request, ct);

            return Ok(quote);
        }

        /// <summary>
        /// Deletes an existing quote based on the specified request.
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator or Inspector role. The request must
        /// include valid quote information in the request body.</remarks>
        /// <param name="request">The details of the quote to delete. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An IActionResult indicating the result of the delete operation.</returns>
        [HttpDelete("deletequote")]
        [Authorize(Roles = "Administrator, Inspector")]
        public async Task<IActionResult> DeleteQuote([FromBody] QuoteDeleteRequest request, CancellationToken ct)
        {
            var quote = await quoteService.DeleteQuote(request, ct);

            return Ok(quote);
        }
    }
}
