using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

namespace CheckMyStar.Apis.Controllers
{
    /// <summary>
    /// Defines API endpoints for role operations.
    /// </summary>
    /// <param name="roleService">Role service</param>
    [ApiController]
    [Route("api/[controller]")]
    public class RoleController(IRoleService roleService) : ControllerBase
    {
        /// <summary>
        /// Generates and returns the next available identifier for a role. 
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The identifier is
        /// generated by the underlying role service and is guaranteed to be unique at the time of generation.</remarks>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of roles that match the specified criteria.</returns>
        [HttpGet("getnextidentifier")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
        {
            var identifier = await roleService.GetNextIdentifier(ct);

            return Ok(identifier);
        }

        /// <summary>
        /// Retrieves a list of roles based on the specified request criteria.
        /// </summary>
        /// <param name="request">The criteria for retrieving roles. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the list of roles that match the specified criteria.</returns>
        [HttpGet("getroles")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> GetRoles([FromQuery] RoleGetRequest request, CancellationToken ct)
        {
            var roles = await roleService.GetRoles(request, ct);

            return Ok(roles);
        }

        /// <summary>
        /// Creates a new role using the specified request data.
        /// </summary>
        /// <param name="request">The details of the role to create. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the created role.</returns>
        [HttpPost("addrole")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> AddRole([FromBody] RoleSaveRequest request, CancellationToken ct)
        {
            var role = await roleService.AddRole(request, ct);

            return Ok(role);
        }

        /// <summary>
        /// Updates an existing role with the specified details.
        /// </summary>
        /// <param name="request">The role information to update. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An <see cref="IActionResult"/> containing the updated role information if the update is successful.</returns>
        [HttpPut("updaterole")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> UpdateRole([FromBody] RoleSaveRequest request, CancellationToken ct)
        {
            var role = await roleService.UpdateRole(request, ct);

            return Ok(role);
        }

        /// <summary>
        /// Deletes an existing role based on the specified request.
        /// </summary>
        /// <remarks>This action is restricted to users with the Administrator role. The request must
        /// include valid role information in the request body.</remarks>
        /// <param name="request">The details of the role to delete. Must not be null.</param>
        /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
        /// <returns>An IActionResult indicating the result of the delete operation.</returns>
        [HttpDelete("deleterole")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteRole([FromQuery] RoleDeleteRequest request, CancellationToken ct)
        {
            var role = await roleService.DeleteRole(request, ct);

            return Ok(role);
        }
    }
}
