using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using CheckMyStar.Apis.Services.Abstractions;
using CheckMyStar.Bll.Requests;

/// <summary>
/// 
/// </summary>
/// <param name="societyService"></param>
[ApiController]
[Route("api/[controller]")]
public class SocietyController(ISocietyService societyService) : ControllerBase
{
    /// <summary>
    /// Generates and returns the next available identifier for a society. 
    /// </summary>
    /// <remarks>This action is restricted to users with the Administrator role. The identifier is
    /// generated by the underlying society service and is guaranteed to be unique at the time of generation.</remarks>
    /// <param name="ct">A cancellation token that can be used to cancel the operation.</param>
    /// <returns>An <see cref="IActionResult"/> containing the next available society identifier.</returns>
    [HttpGet("getnextidentifier")]
    [Authorize(Roles = "Administrator")]
    public async Task<IActionResult> GetNextIdentifier(CancellationToken ct)
    {
        var identifier = await societyService.GetNextIdentifier(ct);

        return Ok(identifier);
    }

    /// <summary>
    /// Crée une nouvelle société.
    /// </summary>
    /// <param name="request">Données de la société</param>
    /// <param name="ct">Jeton d'annulation</param>
    /// <returns>Résultat de la création</returns>
    [HttpPost("addsociety")]
    [Authorize(Roles = "Administrator")]
    public async Task<IActionResult> AddSociety([FromBody] SocietySaveRequest request, CancellationToken ct)
    {
        var result = await societyService.AddSociety(request, ct);

        return Ok(result);
    }

    /// <summary>
    /// Mise à jour d'une société.
    /// </summary>
    /// <param name="request">Données de la société</param>
    /// <param name="ct">Jeton d'annulation</param>
    /// <returns>Résultat de la création</returns>
    [HttpPut("updatesociety")]
    [Authorize(Roles = "Administrator")]
    public async Task<IActionResult> UpdateSociety([FromBody] SocietySaveRequest request, CancellationToken ct)
    {
        var result = await societyService.AddSociety(request, ct);

        return Ok(result);
    }

    /// <summary>
    /// Suppression d'une société.
    /// </summary>
    /// <param name="request">Données de la société</param>
    /// <param name="ct">Jeton d'annulation</param>
    /// <returns>Résultat de la création</returns>
    [HttpDelete("deletesociety")]
    [Authorize(Roles = "Administrator")]
    public async Task<IActionResult> DeleteSociety([FromBody] SocietyDeleteRequest request, CancellationToken ct)
    {
        var result = await societyService.DeleteSociety(request, ct);

        return Ok(result);
    }

    /// <summary>
    /// Récupère toutes les sociétés.
    /// </summary>
    /// <param name="ct">Jeton d'annulation</param>
    [HttpGet("getsocieties")]
    [Authorize(Roles = "Administrator, Inspector")]
    public async Task<IActionResult> GetSocieties(CancellationToken ct)
    {
        var result = await societyService.GetSocieties(ct);

        return result.IsSuccess ? Ok(result) : BadRequest(result);
    }

    /// <summary>
    /// Récupère une société
    /// </summary>
    /// <param name="request"></param>
    /// <param name="ct"></param>
    /// <returns></returns>
    public async Task<IActionResult> GetSociety([FromQuery] SocietyGetRequest request, CancellationToken ct)
    {
        var result = await societyService.GetSociety(request, ct);

        return Ok(result);
    }
}